import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { TWIKOO_CDN_URL, TWIKOO_VERSION } from "../src/config/twikoo";

const OUTPUT_PATH = path.resolve("src/utils/generated/twikooSRI.ts");
const checkMode = process.argv.includes("--check");
const FETCH_TIMEOUT_MS = 10_000;
const FETCH_RETRIES = 3;

function parseGenerated(
  content: string
): { version: string; sri: string } | null {
  const versionMatch = content.match(
    /export const TWIKOO_SRI_VERSION = "([^"]+)";/
  );
  const sriMatch = content.match(/export const TWIKOO_SRI =\s*"([^"]+)";/);

  if (!versionMatch || !sriMatch) return null;

  return {
    version: versionMatch[1],
    sri: sriMatch[1],
  };
}

function buildGenerated(version: string, sri: string): string {
  return `// Auto-generated by scripts/manage-twikoo-sri.ts. Do not edit manually.
export const TWIKOO_SRI_VERSION = "${version}";
export const TWIKOO_SRI = "${sri}";
`;
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms));
}

function formatError(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

async function fetchWithRetry(url: string): Promise<Response> {
  let lastError: unknown = new Error("Unknown fetch error");

  for (let attempt = 1; attempt <= FETCH_RETRIES; attempt += 1) {
    const controller = new AbortController();
    const timeoutHandle = setTimeout(
      () => controller.abort(),
      FETCH_TIMEOUT_MS
    );

    try {
      const res = await fetch(url, { signal: controller.signal });
      if (!res.ok) {
        throw new Error(`HTTP ${res.status}`);
      }
      return res;
    } catch (error) {
      lastError = error;
      if (attempt < FETCH_RETRIES) {
        await sleep(attempt * 500);
      }
    } finally {
      clearTimeout(timeoutHandle);
    }
  }

  throw new Error(
    `Failed to fetch ${url} after ${FETCH_RETRIES} attempts (timeout ${FETCH_TIMEOUT_MS}ms): ${formatError(lastError)}`
  );
}

async function computeSri(url: string): Promise<string> {
  const res = await fetchWithRetry(url);
  const buffer = Buffer.from(await res.arrayBuffer());
  const hash = createHash("sha384").update(buffer).digest("base64");
  return `sha384-${hash}`;
}

async function main() {
  const computedSri = await computeSri(TWIKOO_CDN_URL);

  if (checkMode) {
    const existing = await readFile(OUTPUT_PATH, "utf8").catch(() => "");
    const parsed = parseGenerated(existing);

    if (!parsed) {
      throw new Error(
        `Missing or invalid ${OUTPUT_PATH}. Run: pnpm twikoo:sri:update`
      );
    }

    if (parsed.version !== TWIKOO_VERSION || parsed.sri !== computedSri) {
      throw new Error(
        [
          "Twikoo SRI check failed.",
          `Expected version: ${TWIKOO_VERSION}`,
          `Generated version: ${parsed.version}`,
          `Expected SRI: ${computedSri}`,
          `Generated SRI: ${parsed.sri}`,
          "Run: pnpm twikoo:sri:update",
        ].join("\n")
      );
    }

    console.log("Twikoo SRI check passed.");
    return;
  }

  await writeFile(
    OUTPUT_PATH,
    buildGenerated(TWIKOO_VERSION, computedSri),
    "utf8"
  );
  console.log(`Updated ${OUTPUT_PATH}`);
  console.log(`Version: ${TWIKOO_VERSION}`);
  console.log(`SRI: ${computedSri}`);
}

main().catch(error => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(message);
  process.exit(1);
});
